package admin

import (
	"github.com/knowoff/knowoff/server/internal/webui"
	"net/http"
	"strings"
)

func adminPage(w http.ResponseWriter, r *http.Request, title, intro, body string, data any) {
	webui.Render(w, 200, webui.Page{Title: title, Intro: intro, Area: "admin", Path: r.URL.Path, CSRF: csrfFromContext(r.Context()), Data: data}, body)
}
func adminError(w http.ResponseWriter, r *http.Request, err error, back string) {
	message := "The change could not be saved. Reload the page and check its current state."
	for _, s := range []string{"required", "not approved", "already", "reason", "reviewable", "screen", "invalid", "week must", "changed during", "no active"} {
		if strings.Contains(err.Error(), s) {
			message = err.Error()
			break
		}
	}
	webui.Render(w, 400, webui.Page{Title: "Change not saved", Area: "admin", Path: back, CSRF: csrfFromContext(r.Context()), Data: map[string]string{"Message": message, "Back": back}}, `<div class="error" role="alert">{{.Data.Message}}</div><a class="button secondary" href="{{.Data.Back}}">Return to the workspace</a>`)
}

const applicationsBody = `<h2 style="margin-top:0">Application inbox</h2>{{range .Data.Applications}}<article class="panel"><div class="row spread"><h3>{{.Role}}</h3><span class="status">{{.Status}}</span></div><p>Account <code>{{.AccountID}}</code> · {{.AppliedAt.Format "02 Jan 2006"}}</p>{{if eq .Status "pending"}}<div class="split"><form method="post" action="/admin/portal/applications/{{.ID}}/approve"><input type="hidden" name="csrf_token" value="{{$.CSRF}}"><p>Grant the requested role to this account.</p><button>Approve {{.Role}}</button></form><form method="post" action="/admin/portal/applications/{{.ID}}/reject"><input type="hidden" name="csrf_token" value="{{$.CSRF}}"><label for="reason-{{.ID}}">Reason shown to applicant</label><input id="reason-{{.ID}}" name="reason" maxlength="2000" required><button class="secondary">Reject application</button></form></div>{{else if .Reason}}<p>{{.Reason}}</p>{{end}}</article>{{else}}<p class="empty">No applications yet. Players apply through the contributor studio.</p>{{end}}<h2>Granted roles</h2><div class="table-scroll"><table><thead><tr><th>Account</th><th>Role</th><th>State</th><th>Action</th></tr></thead><tbody>{{range .Data.Grants}}<tr><td><code>{{.AccountID}}</code></td><td>{{.Role}}</td><td>{{if .RevokedAt}}Revoked{{else}}Active{{end}}</td><td>{{if not .RevokedAt}}<form method="post" action="/admin/portal/roles/{{.AccountID}}/revoke"><input type="hidden" name="csrf_token" value="{{$.CSRF}}"><input type="hidden" name="role" value="{{.Role}}"><button class="secondary">Revoke {{.Role}}</button></form>{{end}}</td></tr>{{else}}<tr><td colspan="4">No role grants yet.</td></tr>{{end}}</tbody></table></div>`
const termsBody = `<div class="split"><section><h2 style="margin-top:0">Create a terms version</h2><p>Effective versions are immutable. The latest effective version is shown to contributors; future versions wait until their start date.</p><form method="post" action="/admin/portal/terms"><input type="hidden" name="csrf_token" value="{{.CSRF}}"><label for="version">Version</label><input id="version" name="version" maxlength="100" required><label for="title">Title</label><input id="title" name="title" maxlength="200" required><label for="body">Full contribution terms</label><textarea id="body" name="body" maxlength="50000" required></textarea><label for="active-from">Effective date (UTC)</label><input id="active-from" name="active_from" type="date" required><button>Create version</button></form></section><section><h2 style="margin-top:0">Version history</h2>{{range .Data.Terms}}<details><summary>{{.Version}} · {{.Title}}</summary><p class="small">Effective {{.ActiveFrom.Format "02 Jan 2006 15:04 UTC"}}</p><div class="terms">{{.Body}}</div></details>{{else}}<p class="empty">No terms exist yet. Create the first effective version before inviting contributors.</p>{{end}}</section></div>`
const submissionsReviewBody = `<p class="notice">Approval runs the automated content screen and records your human decision. If the screening provider is unavailable, approval stays blocked. Accepted text earns the existing contribution reward; it does not deploy a media pack.</p>{{range .Data.Submissions}}<article class="panel"><div class="row spread"><span class="status">{{.Status}}</span><span class="small">{{.MediaType}} · terms {{.TermsVersion}}</span></div><p class="preview" style="margin-top:16px">{{.Content}}</p><p class="small">Account <code>{{.AccountID}}</code> · Submission <code>{{.ID}}</code></p>{{if or (eq .Status "submitted") (eq .Status "in_review")}}<div class="split"><form method="post" action="/admin/portal/submissions/{{.ID}}/approve"><input type="hidden" name="csrf_token" value="{{$.CSRF}}"><input type="hidden" name="revision" value="{{.Revision}}"><label class="check"><input type="checkbox" name="human_reviewed" value="yes" required><span>I reviewed this text for safety, originality and the game's tone.</span></label><button>Screen & approve</button></form><form method="post" action="/admin/portal/submissions/{{.ID}}/reject"><input type="hidden" name="csrf_token" value="{{$.CSRF}}"><label for="reason-{{.ID}}">Reason shown to contributor</label><input id="reason-{{.ID}}" name="reason" maxlength="2000" required><button class="secondary">Reject submission</button></form></div>{{else if .RejectionReason}}<p>{{.RejectionReason}}</p>{{end}}</article>{{else}}<p class="empty">No submitted text is waiting. Contributors send drafts here when they are ready.</p>{{end}}`
const challengeAdminBody = `<div class="split"><section><h2 style="margin-top:0">Schedule a weekly topic</h2><p>Select approved text as the Nown. Its scheduled week begins on Monday at 00:00 UTC.</p><form method="post" action="/admin/portal/challenge/topic"><input type="hidden" name="csrf_token" value="{{.CSRF}}"><label for="week">Week beginning (Monday, UTC)</label><input id="week" name="week_start" type="date" required><label for="topic-media">Approved text Nown</label><select id="topic-media" name="nown_media_id" required><option value="">Choose a reviewed contribution</option>{{range .Data.Topics}}<option value="{{.ID}}">{{.Content}}</option>{{end}}</select><button>Schedule topic</button></form></section><section><h2 style="margin-top:0">Current week</h2>{{if .Data.Topic}}<p>{{.Data.Topic.WeekStart.Format "02 Jan 2006"}} — {{.Data.Topic.WeekEnd.Format "02 Jan 2006"}}</p><p>Topic <code>{{.Data.Topic.ID}}</code></p>{{if .Data.Topic.ClosedAt}}<p class="status">Closed</p>{{else}}<form method="post" action="/admin/portal/challenge/{{.Data.Topic.ID}}/close"><input type="hidden" name="csrf_token" value="{{.CSRF}}"><p>Closing ends intake and voting, chooses the winner and applies the winner reward once.</p><label class="check"><input type="checkbox" name="confirm_close" value="yes" required><span>I want to close this week now.</span></label><button class="danger">Close week & award winner</button></form>{{end}}{{else}}<p class="empty">No topic is scheduled for the current week.</p>{{end}}</section></div><h2>Entry screening queue</h2><p class="muted">Submitted and screening entries stay private until both the automated screen and your review pass.</p>{{range .Data.Entries}}<article class="panel"><div class="row spread"><span class="status">{{.Status}}</span><span>{{.VoteCount}} votes</span></div><p class="preview" style="margin-top:16px">{{.Content}}</p><p class="small">Account <code>{{.AccountID}}</code></p>{{if or (eq .Status "submitted") (eq .Status "screening")}}<div class="split"><form method="post" action="/admin/portal/challenge/entries/{{.ID}}/approve"><input type="hidden" name="csrf_token" value="{{$.CSRF}}"><label class="check"><input type="checkbox" name="human_reviewed" value="yes" required><span>I reviewed this response for public display.</span></label><button>Screen & make public</button></form><form method="post" action="/admin/portal/challenge/entries/{{.ID}}/reject"><input type="hidden" name="csrf_token" value="{{$.CSRF}}"><label for="reason-{{.ID}}">Rejection reason</label><input id="reason-{{.ID}}" name="reason" maxlength="2000" required><button class="secondary">Reject & reopen slot</button></form></div>{{else if .RejectionReason}}<p>{{.RejectionReason}}</p>{{end}}</article>{{else}}<p class="empty">No entries yet for this topic. New submissions will appear here before players can see them.</p>{{end}}`
