package media

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"

	"github.com/knowoff/knowoff/server/pkg/gamecontract"
)

type TextCertificationCell struct {
	Mode              gamecontract.ModeID `json:"mode"`
	TableSize         int                 `json:"table_size"`
	Deals             int                 `json:"deals"`
	Failures          int                 `json:"failures"`
	UnobservedCards   int                 `json:"unobserved_cards"`
	DistinctSchedules int                 `json:"distinct_schedules"`
	DistinctNowns     int                 `json:"distinct_nowns"`
}

// This is sampled retained-card evidence. It does not claim exhaustive action
// coverage, humor, human review, actual participants, rights or release approval.
type TextCertification struct {
	SchemaVersion   int                     `json:"schema_version"`
	SnapshotSHA256  string                  `json:"snapshot_sha256"`
	RulesVersion    string                  `json:"rules_version"`
	Language        string                  `json:"language"`
	TuningSHA256    string                  `json:"tuning_sha256"`
	ReplaySHA256    string                  `json:"replay_sha256"`
	Scope           string                  `json:"scope"`
	Synthetic       bool                    `json:"synthetic"`
	Passed          bool                    `json:"passed"`
	ProductionReady bool                    `json:"production_ready"`
	Cells           []TextCertificationCell `json:"cells"`
	Errors          []string                `json:"errors"`
}

func TextTuningSHA256(tuning TextDealTuning) string {
	raw, _ := json.Marshal(tuning)
	return ContentHash(raw)
}

// TextReplay contains privileged deterministic inputs. Store it as a private
// hash-bound replay.json artifact, never in general logs or player payloads.
type TextReplay struct {
	SchemaVersion  int            `json:"schema_version"`
	Algorithm      string         `json:"algorithm"`
	SnapshotSHA256 string         `json:"snapshot_sha256"`
	Tuning         TextDealTuning `json:"tuning"`
	Samples        int            `json:"samples"`
	Seed           int64          `json:"seed"`
}

func NewTextReplay(snapshot *TextSnapshot, tuning TextDealTuning, samples int, seed int64) TextReplay {
	return TextReplay{SchemaVersion: 2, Algorithm: "text-deal-v1", SnapshotSHA256: snapshot.SHA256(), Tuning: tuning, Samples: samples, Seed: seed}
}

func CertifyText(snapshot *TextSnapshot, tuning TextDealTuning, samples int, seed int64) TextCertification {
	report := TextCertification{SchemaVersion: 2, Scope: "sampled-complete-schedule-retained-cards", TuningSHA256: TextTuningSHA256(tuning), Passed: true}
	if snapshot == nil || !textTuningValid(tuning) || samples < 1 || samples > tuning.MaxSearchNodes {
		report.Passed = false
		report.Errors = []string{"invalid certification inputs or sample bound"}
		return report
	}
	m := snapshot.bundle.Manifest
	report.SnapshotSHA256 = snapshot.hash
	report.RulesVersion = m.RulesVersion
	report.Language = m.Language
	report.Synthetic = m.Synthetic
	replay, _ := json.Marshal(NewTextReplay(snapshot, tuning, samples, seed))
	report.ReplaySHA256 = ContentHash(replay)
	modes := append([]gamecontract.ModeID(nil), m.Modes...)
	sort.Slice(modes, func(i, j int) bool { return modes[i] < modes[j] })
	for _, mode := range modes {
		for _, size := range []int{4, 6} {
			cell := TextCertificationCell{Mode: mode, TableSize: size}
			seenCards := map[string]bool{}
			seenNowns := map[string]bool{}
			seenSchedules := map[string]bool{}
			for sample := 0; sample < samples; sample++ {
				cell.Deals++
				randomness := TextRandomness{Schedule: seed + int64(sample), Hands: seed + int64(sample) + 1, System: seed + int64(sample) + 2}
				deal, err := snapshot.Deal(mode, size, tuning, randomness)
				if err != nil {
					cell.Failures++
					continue
				}
				var ids []string
				for _, nown := range deal.Nowns {
					seenNowns[nown.ID] = true
					ids = append(ids, nown.ID)
				}
				raw, _ := json.Marshal(ids)
				seenSchedules[ContentHash(raw)] = true
				for _, hand := range deal.Hands {
					for _, card := range hand.Cards {
						seenCards[card.ID] = true
					}
					for _, card := range hand.Reserve {
						seenCards[card.ID] = true
					}
				}
			}
			for _, card := range snapshot.bundle.Cards {
				if textHasMode(card.Modes, mode) && !seenCards[card.ID] {
					cell.UnobservedCards++
				}
			}
			cell.DistinctNowns = len(seenNowns)
			cell.DistinctSchedules = len(seenSchedules)
			if cell.Failures != 0 || cell.UnobservedCards != 0 {
				report.Passed = false
				report.Errors = append(report.Errors, fmt.Sprintf("%s/%d: incomplete sampled retained-card evidence", mode, size))
			}
			report.Cells = append(report.Cells, cell)
		}
	}
	return report
}

// Gate evidence is supplied by an authorized editorial/release workflow, never
// generated by CertifyText. These references bind actual external review and
// engine proof records; validating their shape does not manufacture that work.
type TextGateCell struct {
	Mode            gamecontract.ModeID `json:"mode"`
	TableSize       int                 `json:"table_size"`
	Passed          bool                `json:"passed"`
	RecordReference string              `json:"record_reference"`
	EvidenceSHA256  string              `json:"evidence_sha256"`
}
type TextGateEvidence struct {
	SchemaVersion  int            `json:"schema_version"`
	SnapshotSHA256 string         `json:"snapshot_sha256"`
	RulesVersion   string         `json:"rules_version"`
	Language       string         `json:"language"`
	Gate           string         `json:"gate"`
	ActorReference string         `json:"actor_reference"`
	TuningSHA256   string         `json:"tuning_sha256"`
	Cells          []TextGateCell `json:"cells"`
}

func (s *TextSnapshot) ValidateActivation(rules string, tuning TextDealTuning) error {
	if s == nil || s.bundle.Manifest.Synthetic || s.bundle.Manifest.RulesVersion != rules || !textTuningValid(tuning) {
		return fmt.Errorf("release is not production eligible")
	}
	m := s.bundle.Manifest
	var technical TextCertification
	if err := textStrictJSON(s.bundle.Artifacts["technical.json"], &technical); err != nil {
		return fmt.Errorf("missing or invalid technical certificate")
	}
	if technical.SchemaVersion != 2 || technical.SnapshotSHA256 != s.hash || technical.RulesVersion != rules || technical.Language != m.Language || technical.TuningSHA256 != TextTuningSHA256(tuning) || technical.Scope != "sampled-complete-schedule-retained-cards" || !technical.Passed || technical.Synthetic || technical.ProductionReady || len(technical.Errors) != 0 || !textHashValid(technical.ReplaySHA256) {
		return fmt.Errorf("technical certificate does not match release/tuning")
	}
	var replay TextReplay
	if err := textStrictJSON(s.bundle.Artifacts["replay.json"], &replay); err != nil {
		return fmt.Errorf("missing or invalid private replay inputs")
	}
	if replay.SchemaVersion != 2 || replay.Algorithm != "text-deal-v1" || replay.SnapshotSHA256 != s.hash || !reflect.DeepEqual(replay.Tuning, tuning) || replay.Samples < 1 || replay.Samples > tuning.MaxSearchNodes || ContentHash(s.bundle.Artifacts["replay.json"]) != technical.ReplaySHA256 {
		return fmt.Errorf("replay inputs do not match technical certificate")
	}
	// Recompute the sampled proof from its bounded, exact inputs. A self-reported
	// Passed flag or edited aggregate counter is not certification evidence.
	if expected := CertifyText(s, tuning, replay.Samples, replay.Seed); !reflect.DeepEqual(expected, technical) {
		return fmt.Errorf("technical certificate cannot be reproduced")
	}
	seen := map[string]bool{}
	for _, cell := range technical.Cells {
		key := fmt.Sprintf("%s/%d", cell.Mode, cell.TableSize)
		if !textHasMode(m.Modes, cell.Mode) || (cell.TableSize != 4 && cell.TableSize != 6) || seen[key] || cell.Deals < 1 || cell.Failures != 0 || cell.UnobservedCards != 0 || cell.DistinctSchedules < 1 || cell.DistinctNowns < cell.TableSize/2 {
			return fmt.Errorf("incomplete technical mode/size evidence")
		}
		seen[key] = true
	}
	if len(seen) != 2*len(m.Modes) {
		return fmt.Errorf("missing technical mode/size evidence")
	}
	for _, gate := range []string{"editorial", "actions", "screening", "release"} {
		var evidence TextGateEvidence
		if err := textStrictJSON(s.bundle.Artifacts[gate+".json"], &evidence); err != nil {
			return fmt.Errorf("missing %s gate", gate)
		}
		if evidence.SchemaVersion != 2 || evidence.SnapshotSHA256 != s.hash || evidence.RulesVersion != rules || evidence.Language != m.Language || evidence.Gate != gate || evidence.TuningSHA256 != TextTuningSHA256(tuning) || !gamecontract.ValidIdentifier(evidence.ActorReference) {
			return fmt.Errorf("%s gate does not match release", gate)
		}
		seen = map[string]bool{}
		for _, cell := range evidence.Cells {
			key := fmt.Sprintf("%s/%d", cell.Mode, cell.TableSize)
			if !textHasMode(m.Modes, cell.Mode) || (cell.TableSize != 4 && cell.TableSize != 6) || seen[key] || !cell.Passed || !gamecontract.ValidIdentifier(cell.RecordReference) || !textHashValid(cell.EvidenceSHA256) {
				return fmt.Errorf("invalid %s mode/size evidence", gate)
			}
			seen[key] = true
		}
		if len(seen) != 2*len(m.Modes) {
			return fmt.Errorf("incomplete %s gate", gate)
		}
	}
	return nil
}
